#!/usr/bin/env python3
"""Generate ccc_mapping.toml for code-complexity-comparator (ccc-rs).

Pins each Rust method (rust_class = impl struct) to its Java counterpart
(other_path = Java reader file), matching reader struct <-> Java reader file by
canonical name and method by canonical name + semantic override aliases. Java
functions have no enclosing_type in the report, so the Java side is pinned by
file path, not class.

Usage:
  python3 audit/gen_ccc_mapping.py /tmp/rust.json /tmp/java_gpl.json /tmp/java_bsd.json > ccc_mapping.toml
"""
import json, re, collections, os, sys

def canon(s):
    return re.sub(r'[^a-z0-9]', '', s.lower())

rust = json.load(open(sys.argv[1]))['functions']
java = []
for p in sys.argv[2:]:
    java += json.load(open(p))['functions']

def stem(path):
    return os.path.basename(path).rsplit('.', 1)[0]

jidx = collections.defaultdict(list)
jstems = set()
for f in java:
    s = stem(f['location']['file']); jstems.add(s)
    jidx[(canon(s), canon(f['name']))].append((f['location']['file'], f['name']))
jstem_canon = {canon(s): s for s in jstems}

# Rust struct canon -> Java file stem canon (known renames)
alias = {
    'czireader': 'zeissczireader', 'ndpireader': 'hamamatsundpireader',
    'lsmreader': 'zeisslsmreader', 'vmsreader': 'hamamatsuvmsreader',
    'dcimgreader': 'hamamatsudcimgreader', 'oirreader': 'olympusoirreader',
    'aplreader': 'olympusaplreader', 'quicktimereader': 'qtreader',
    'nikonnisreader': 'nikonreader', 'openlabliffreader': 'openlabreader',
    'feiphilipsreader': 'feireader', 'feiserreader': 'serreader',
}
# Rust method name -> candidate Java method names (semantic override points)
malias = {
    'set_id': ['initFile'], 'init_file': ['initFile'],
    'is_this_type_by_bytes': ['isThisType'], 'is_this_type': ['isThisType'],
    'is_this_type_by_name': ['isThisType'], 'open_bytes_region': ['openBytes'],
    'get_series_used_files': ['getSeriesUsedFiles'], 'reopen_file': ['reopenFile'],
}

rmethods = collections.defaultdict(list)
for f in rust:
    if f.get('enclosing_type'):
        rmethods[f['enclosing_type']].append(f)

entries = []; seen = set()
for struct, fns in rmethods.items():
    ck = canon(struct)
    target = ck if ck in jstem_canon else alias.get(ck)
    if not target or target not in jstem_canon:
        cand = [c for c in jstem_canon if len(ck) > 6 and (ck in c or c in ck) and c.endswith('reader')]
        target = cand[0] if len(cand) == 1 else None
    if not target:
        continue
    used_j = set()
    for f in fns:
        names = [f['name']] + malias.get(f['name'], [])
        for cand_name in names:
            hits = [h for h in jidx.get((target, canon(cand_name)), []) if h[1] not in used_j]
            if hits:
                jfile, jname = hits[0]; used_j.add(jname)
                key = (struct, f['name'])
                if key in seen:
                    break
                seen.add(key)
                entries.append((f['name'], struct, jname, os.path.basename(jfile)))
                break

# Codec functions: Rust implements each Java `*Codec` class as a standalone
# `decompress_<name>` function in src/common/codec.rs. Pin them to the Java codec
# class's `decompress`/`compress` so audits over the loci/formats/codec package
# pair them instead of reporting structural false positives.
CODEC_MAP = [
    ("decompress_msrle", "MSRLECodec.java"),
    ("decompress_msvideo", "MSVideoCodec.java"),
    ("decompress_rpza", "RPZACodec.java"),
    ("decompress_qtrle", "QTRLECodec.java"),
    ("decompress_lzw", "LZWCodec.java"),
    ("decompress_packbits", "PackbitsCodec.java"),
    ("decompress_zstd", "ZstdCodec.java"),
    ("decompress_jpeg2000", "JPEG2000Codec.java"),
    ("decompress_jpeg", "JPEGCodec.java"),
    ("decompress_nikon", "NikonCodec.java"),
    ("decompress_huffman", "HuffmanCodec.java"),
    ("decompress_lzo", "LZOCodec.java"),
    ("decompress_jpegxr", "JPEGXRCodec.java"),
    ("decompress_mjpb", "MJPBCodec.java"),
    ("targa_rle_decompress", "TargaRLECodec.java"),
]
for rn, opath in CODEC_MAP:
    entries.append((rn, "\0codec", "decompress", opath))  # sentinel class = codec free fn

out = sys.stdout
out.write("# Auto-generated by audit/gen_ccc_mapping.py — reader-struct <-> Java-reader-file\n")
out.write("# method mapping for ccc-rs. rust_class = Rust impl struct; other_path = Java reader\n")
out.write("# file. Pins by canonical name + semantic override aliases (set_id->initFile,\n")
out.write("# is_this_type->isThisType) so trait-method collisions match the correct reader.\n")
out.write("collapse_other_duplicates = true\n\n")
for rn, rc, on, opath in sorted(entries):
    out.write("[[entries]]\n")
    out.write(f'rust = "{rn}"\n')
    if rc == "\0codec":
        out.write('rust_path = "common/codec.rs"\n')
    else:
        out.write(f'rust_class = "{rc}"\n')
    out.write(f'other = "{on}"\nother_path = "{opath}"\n\n')
sys.stderr.write(f"entries={len(entries)} structs={len({e[1] for e in entries if e[1] != chr(0)+'codec'})} codecs={len(CODEC_MAP)}\n")
