use std::fs::File;
use std::io::{BufWriter, Write};
use std::path::{Path, PathBuf};

use crate::common::error::{BioFormatsError, Result};
use crate::common::metadata::ImageMetadata;
use crate::common::pixel_type::PixelType;
use crate::common::writer::{expected_plane_len, FormatWriter};

pub struct JavaWriter {
    path: Option<PathBuf>,
    meta: Option<ImageMetadata>,
    out: Option<BufWriter<File>>,
}

impl JavaWriter {
    pub fn new() -> Self {
        JavaWriter {
            path: None,
            meta: None,
            out: None,
        }
    }

    fn write_header(&mut self, path: &Path) -> Result<()> {
        let class_name = path
            .file_stem()
            .and_then(|stem| stem.to_str())
            .unwrap_or("Image");
        let out = self.out.as_mut().ok_or(BioFormatsError::NotInitialized)?;
        writeln!(out, "//").map_err(BioFormatsError::Io)?;
        writeln!(out, "// {class_name}.java").map_err(BioFormatsError::Io)?;
        writeln!(out, "//").map_err(BioFormatsError::Io)?;
        writeln!(out).map_err(BioFormatsError::Io)?;
        writeln!(out, "// Generated by Bio-Formats").map_err(BioFormatsError::Io)?;
        writeln!(out).map_err(BioFormatsError::Io)?;
        writeln!(out, "public class {class_name} {{").map_err(BioFormatsError::Io)?;
        writeln!(out).map_err(BioFormatsError::Io)?;
        Ok(())
    }

    fn write_footer(&mut self) -> Result<()> {
        if let Some(out) = self.out.as_mut() {
            writeln!(out, "}}").map_err(BioFormatsError::Io)?;
            out.flush().map_err(BioFormatsError::Io)?;
        }
        Ok(())
    }
}

impl Default for JavaWriter {
    fn default() -> Self {
        Self::new()
    }
}

impl FormatWriter for JavaWriter {
    fn is_this_type(&self, path: &Path) -> bool {
        path.extension()
            .and_then(|e| e.to_str())
            .map(|e| e.eq_ignore_ascii_case("java"))
            .unwrap_or(false)
    }

    fn set_id(&mut self, path: &Path) -> Result<()> {
        self.meta.as_ref().ok_or_else(|| {
            BioFormatsError::Format("set_metadata must be called before set_id".into())
        })?;
        let file = File::create(path).map_err(BioFormatsError::Io)?;
        self.out = Some(BufWriter::new(file));
        self.write_header(path)?;
        self.path = Some(path.to_path_buf());
        Ok(())
    }

    fn close(&mut self) -> Result<()> {
        self.write_footer()?;
        self.out = None;
        self.path = None;
        self.meta = None;
        Ok(())
    }

    fn set_metadata(&mut self, meta: &ImageMetadata) -> Result<()> {
        match meta.pixel_type {
            PixelType::Int8
            | PixelType::Uint8
            | PixelType::Uint16
            | PixelType::Uint32
            | PixelType::Int32
            | PixelType::Float32
            | PixelType::Float64 => {}
            other => {
                return Err(BioFormatsError::UnsupportedFormat(format!(
                    "JavaWriter unsupported image type {other:?}"
                )));
            }
        }
        self.meta = Some(meta.clone());
        Ok(())
    }

    fn save_bytes(&mut self, plane_index: u32, data: &[u8]) -> Result<()> {
        let meta = self.meta.as_ref().ok_or(BioFormatsError::NotInitialized)?;
        let expected = expected_plane_len(meta)?;
        if data.len() < expected {
            return Err(BioFormatsError::Format(format!(
                "JavaWriter plane {plane_index} has {} bytes, expected {expected} bytes or more",
                data.len()
            )));
        }
        let width = meta.size_x as usize;
        let height = meta.size_y as usize;
        let little = meta.is_little_endian;
        let var_name = format!("series{}Plane{}", self.series(), plane_index);
        let out = self.out.as_mut().ok_or(BioFormatsError::NotInitialized)?;
        match meta.pixel_type {
            PixelType::Int8 | PixelType::Uint8 => {
                write_java_plane(out, "byte", &var_name, width, height, |i| {
                    (data[i] as i8).to_string()
                })?;
            }
            PixelType::Uint16 => {
                write_java_plane(out, "short", &var_name, width, height, |i| {
                    let off = i * 2;
                    let bytes = [data[off], data[off + 1]];
                    let value = if little {
                        u16::from_le_bytes(bytes)
                    } else {
                        u16::from_be_bytes(bytes)
                    };
                    (value as i16).to_string()
                })?;
            }
            PixelType::Uint32 | PixelType::Int32 => {
                write_java_plane(out, "int", &var_name, width, height, |i| {
                    let off = i * 4;
                    let bytes = [data[off], data[off + 1], data[off + 2], data[off + 3]];
                    let value = if little {
                        u32::from_le_bytes(bytes)
                    } else {
                        u32::from_be_bytes(bytes)
                    };
                    (value as i32).to_string()
                })?;
            }
            PixelType::Float32 => {
                write_java_plane(out, "float", &var_name, width, height, |i| {
                    let off = i * 4;
                    let bytes = [data[off], data[off + 1], data[off + 2], data[off + 3]];
                    let value = if little {
                        f32::from_le_bytes(bytes)
                    } else {
                        f32::from_be_bytes(bytes)
                    };
                    java_float_string(value)
                })?;
            }
            PixelType::Float64 => {
                write_java_plane(out, "double", &var_name, width, height, |i| {
                    let off = i * 8;
                    let bytes = [
                        data[off],
                        data[off + 1],
                        data[off + 2],
                        data[off + 3],
                        data[off + 4],
                        data[off + 5],
                        data[off + 6],
                        data[off + 7],
                    ];
                    let value = if little {
                        f64::from_le_bytes(bytes)
                    } else {
                        f64::from_be_bytes(bytes)
                    };
                    java_double_string(value)
                })?;
            }
            PixelType::Int16 | PixelType::Bit => unreachable!("validated in set_metadata"),
        }
        Ok(())
    }

    fn can_do_stacks(&self) -> bool {
        true
    }
}

fn write_java_plane<F>(
    out: &mut BufWriter<File>,
    java_type: &str,
    var_name: &str,
    width: usize,
    height: usize,
    mut value_at: F,
) -> Result<()>
where
    F: FnMut(usize) -> String,
{
    writeln!(out, "  public {java_type}[][] {var_name} = {{").map_err(BioFormatsError::Io)?;
    let mut i = 0usize;
    for y in 0..height {
        write!(out, "    {{").map_err(BioFormatsError::Io)?;
        for x in 0..width {
            write!(out, "{}", value_at(i)).map_err(BioFormatsError::Io)?;
            i += 1;
            if x < width - 1 {
                write!(out, ", ").map_err(BioFormatsError::Io)?;
            } else {
                write!(out, "}}").map_err(BioFormatsError::Io)?;
            }
        }
        if y < height - 1 {
            writeln!(out, ",").map_err(BioFormatsError::Io)?;
        } else {
            writeln!(out).map_err(BioFormatsError::Io)?;
        }
    }
    writeln!(out, "  }};").map_err(BioFormatsError::Io)?;
    writeln!(out).map_err(BioFormatsError::Io)?;
    Ok(())
}

fn java_float_string(value: f32) -> String {
    if value.is_finite() && value.fract() == 0.0 {
        format!("{value:.1}")
    } else {
        value.to_string()
    }
}

fn java_double_string(value: f64) -> String {
    if value.is_finite() && value.fract() == 0.0 {
        format!("{value:.1}")
    } else {
        value.to_string()
    }
}
